import { type Config } from "tailwindcss";

export default {
  content: ["./src/**/*.tsx"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: {
          DEFAULT: "var(--color-error-500)",
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          200: "var(--color-error-200)",
          300: "var(--color-error-300)",
          400: "var(--color-error-400)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
          800: "var(--color-error-800)",
          900: "var(--color-error-900)",
        },
        warning: {
          DEFAULT: "var(--color-warning-500)",
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
        },
        success: {
          DEFAULT: "var(--color-success-500)",
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
        },
        info: {
          DEFAULT: "var(--color-info-500)",
          50: "var(--color-info-50)",
          100: "var(--color-info-100)",
          200: "var(--color-info-200)",
          300: "var(--color-info-300)",
          400: "var(--color-info-400)",
          500: "var(--color-info-500)",
          600: "var(--color-info-600)",
          700: "var(--color-info-700)",
          800: "var(--color-info-800)",
          900: "var(--color-info-900)",
        },
        primary: {
          DEFAULT: "var(--color-primary-500)", // Add this line
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary-500)", // Add this line
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
        },
        tertiary: {
          DEFAULT: "var(--color-tertiary-500)", // Add this line
          50: "var(--color-tertiary-50)",
          100: "var(--color-tertiary-100)",
          200: "var(--color-tertiary-200)",
          300: "var(--color-tertiary-300)",
          400: "var(--color-tertiary-400)",
          500: "var(--color-tertiary-500)",
          600: "var(--color-tertiary-600)",
          700: "var(--color-tertiary-700)",
          800: "var(--color-tertiary-800)",
          900: "var(--color-tertiary-900)",
        },
        quaternary: {
          DEFAULT: "var(--color-quaternary-500)", // Add this line
          50: "var(--color-quaternary-50)",
          100: "var(--color-quaternary-100)",
          200: "var(--color-quaternary-200)",
          300: "var(--color-quaternary-300)",
          400: "var(--color-quaternary-400)",
          500: "var(--color-quaternary-500)",
          600: "var(--color-quaternary-600)",
          700: "var(--color-quaternary-700)",
          800: "var(--color-quaternary-800)",
          900: "var(--color-quaternary-900)",
        },
        background: {
          default: "var(--color-background-default)",
          paper: "var(--color-background-paper)",
          level1: "var(--color-background-level1)",
          level2: "var(--color-background-level2)",
          level3: "var(--color-background-level3)",
          light: "var(--color-background-light)",
          dark: "var(--color-background-dark)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          accent: "var(--color-text-accent)",
        },
        border: {
          default: "var(--color-border-default)",
          light: "var(--color-border-light)",
          dark: "var(--color-border-dark)",
        },
        light: {
          background: {
            default: "var(--color-light-background-default)",
            paper: "var(--color-light-background-paper)",
            level1: "var(--color-light-background-level1)",
            level2: "var(--color-light-background-level2)",
            level3: "var(--color-light-background-level3)",
            light: "var(--color-light-background-light)",
            dark: "var(--color-light-background-dark)",
          },
          text: {
            primary: "var(--color-light-text-primary)",
            secondary: "var(--color-light-text-secondary)",
            accent: "var(--color-light-text-accent)",
          },
          border: {
            default: "var(--color-light-border-default)",
            light: "var(--color-light-border-light)",
            dark: "var(--color-light-border-dark)",
          },
        },
        dark: {
          background: {
            default: "var(--color-dark-background-default)",
            paper: "var(--color-dark-background-paper)",
            level1: "var(--color-dark-background-level1)",
            level2: "var(--color-dark-background-level2)",
            level3: "var(--color-dark-background-level3)",
            light: "var(--color-dark-background-light)",
            dark: "var(--color-dark-background-dark)",
          },
          text: {
            primary: "var(--color-dark-text-primary)",
            secondary: "var(--color-dark-text-secondary)",
            accent: "var(--color-dark-text-accent)",
          },
          border: {
            default: "var(--color-dark-border-default)",
            light: "var(--color-dark-border-light)",
            dark: "var(--color-dark-border-dark)",
          },
        },
      },
      spacing: {
        128: "32rem",
        144: "36rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Merriweather", "serif"],
      },
      boxShadow: {
        "elevation-0": "none",
        "elevation-1": "0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)",
        "elevation-2": "0 3px 6px rgba(0,0,0,0.15), 0 2px 4px rgba(0,0,0,0.12)",
        "elevation-3":
          "0 10px 20px rgba(0,0,0,0.15), 0 3px 6px rgba(0,0,0,0.10)",
        "elevation-4":
          "0 15px 25px rgba(0,0,0,0.15), 0 5px 10px rgba(0,0,0,0.05)",
        "elevation-5": "0 20px 40px rgba(0,0,0,0.2)",
      },
    },
  },
  plugins: [],
} satisfies Config;
